import "./globals.css";
import { fetchData } from "@/lib/fetchData";
import { RootLayoutQuery } from "@/queries/rootLayout.graphql";
import NavBar from "@/components/NavBar/navBar";
import ClientNavbar from "@/components/NavBar/navBarClient";
import { cormorant, montserrat, saira } from "@/lib/font";

const getData = async () => {
	const { data } = await fetchData(RootLayoutQuery.loc.source.body);
	return data?.rootLayout?.data?.attributes || [];
};

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	const { navMenu, logo } = await getData();
	return (
		<html
			lang="en"
			className={`${cormorant.variable} ${montserrat.variable} ${saira.variable}`}
		>
			<body>
				<ClientNavbar>
					<NavBar navItems={navMenu} logo={logo} />
				</ClientNavbar>
				{children}
			</body>
		</html>
	);
}
